const age = 42;
console.log("type of age is", typeof age);
const text = "Hello, world!";
console.log("type of text is", typeof text);
const permission = true;
console.log("type of permission is", typeof permission);
const emptyValue = null;
console.log("type of emptyValue is", typeof emptyValue); 
const variable = undefined;
console.log("type of variable is", typeof variable);
const symbol = Symbol("symbol");
console.log("type of symbol is", typeof symbol);
const cup = { color: "red" };
console.log("type of cup is", typeof cup);
const array = [1, 2, 3];
console.log("type of array is", typeof array); 
const func = function() { return "I am a function"; };
console.log("type of function is", typeof func);
const theBiggestInt = BigInt(9007199254740991);
console.log("type of theBiggestInt is", typeof theBiggestInt);